### ISSUE TITLE
Install build: Composer Dependencies Installed failing

### ISSUE THREAD

**Issue by richjenks** [RNGR/Directus#1080]
- Followed steps at https://github.com/RNGR/Directus/wiki/1.-Installation-&-Configuration#installation
- Downloaded zip of build branch (https://github.com/RNGR/Directus/tree/build)
- At Confirmation page, Composer Dependencies Installed is failing

Clicking Install just reloads the Confirmation page. There isn't a composer.json in `/api/`, which is presumably desirable as it's a build branch, but it's breaking the install process.

![screenshot_111615_031537_pm](https://cloud.githubusercontent.com/assets/1795615/11185490/e51d4034-8c74-11e5-8a6d-d3cb1060bd67.jpg)

I found that the page is just checking for the presence of `api/vendor/autoload.php` so I tried creating it but got another error, so my guess would be that the dependencies for the API are simply missing from the build branch.

**Comment by WellingGuzman** [comment]
Thanks @richjenks for let us know, I'd looking at this one, yeah it actually missing the dependencies on the build branch.

**Comment by benhaynes** [comment]
Thanks for finding this @richjenks 

@WellingGuzman – all the more reason to get the `build` branch up to date today!

**Comment by richjenks** [comment]
Hi @benhaynes & @WellingGuzman  no probs, happy to help! Looking forward to getting Directus working because it looks pretty sweet.

**Comment by richjenks** [comment]
Confirmed fix, cheers guys!

**Comment by richjenks** [comment]
@benhaynes @WellingGuzman I've reported 2 issues I've found (#1100 & #1101) but also have 2 issues that might just be me being silly rather than a software issue:

1. How do you delete or rename a table from the admin area?
1. How do you define relationships? Many-to-many and Many-to-one responses are a bit confusing (e.g. selecting one still shows options for tinyint datatype) and it's unclear how to define table and column foreign key.

Additionally, from within the relationship options (cog next to datatype) there's a mandatory "Template" field with no explanation.

Sorry if this is the wrong forum for such questions, let me know if they should go somewhere else!

**Comment by benhaynes** [comment]
Hey @richjenks – this is a perfectly good way to submit issues like this... and is much appreciated!

1. By design, there is no way to rename or delete a table (or field) from within Directus. We (currently) see this as a risky feature to have since you could easily lose a lot of data or break connections to existing applications. We're looking into building a stand-alone extension for these DB admin tools – or adding enough safety measures so that they can be incorporated into the Settings area.
2. We 100% agree – there's a ticket open to clear up this confusion. I've moved this to 'major` so that it is resolved more expeditiously. I'll also open up a stand-alone ticket for clarifying the relational options/parameters.

Thanks!!
