### ISSUE TITLE
Can't sort by relational columns in list view

### ISSUE THREAD

**Issue by jmsrngr** [RNGR/Directus#452]
Sorting on a relational column works fine. However, if I am filtering by a separate relational column and then try sorting the original relational column it does not function properly.

**Comment by WellingGuzman** [comment]
@benhaynes can you explain to me this one?

**Comment by benhaynes** [comment]
@WellingGuzman I'm not 100% sure what Justin meant – but the issue as I see it is that you can not sort items on the listing page by relational columns. If there's a many-to-one column and you sort on it (clicking the column header) it is not ordered by the relational information... it seems to be ordered by the ID value instead.

This would be an AMAZING issue to solve, but I don't know how hard it is.

**Comment by benhaynes** [comment]
You can see here that ordering this field does **not** order the results. This is because this is a relational field (saves IDs, not values) – we should ideally figure out a way to sort by these relational values.

![screen shot 2015-03-08 at 7 17 16 pm](https://cloud.githubusercontent.com/assets/522079/6548213/e7e1d45c-c5c7-11e4-89ec-44f5230ea1c0.png)

**Comment by WellingGuzman** [comment]
This one was solved by PR #702
