### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#719]
This query fails if I try to view the permissions for a user group. I can add new groups, but not view/edit their permissions.

http://www.reddit.com/r/webdev/comments/2zcbv7/we_just_released_a_free_and_opensource_backbonejs/cphy9e5

![jq3poja](https://cloud.githubusercontent.com/assets/522079/6695758/07dd44fa-ccba-11e4-9261-af72d890ca15.png)

**Comment by jwdeitch** [comment]
The query is wrong, it should be:
```SELECT * FROM directus_privileges WHERE 'group_id' = '1' GROUP BY 'group_id','table_name','status_id'```

I'll try to see why the query builder is handling it like this

**Comment by benhaynes** [comment]
The query in the screenshot seems to be working fine for me, and I don't see anything wrong with the syntax:

```SELECT `directus_privileges`.* FROM `directus_privileges` WHERE `group_id` = '1' GROUP BY `group_id`,`table_name`,`status_id````

This came from the same user as this issue: https://github.com/RNGR/Directus/issues/720

I assume this is due to inadequate database user permissions. Will re-open if it occurs again.

**Comment by tjmb** [comment]
I'm experiencing this issue too. When I run that query directly in my database, I get the following response:

Unknown column 'status_id' in 'group statement'

I checked the structure of my directus_privilages table and there's no column named status_id. I'm assuming this was either omitted from the setup procedure or the query should not contain a reference to that column. Which would be the correct solution?

Thanks!

**Comment by benhaynes** [comment]
Thanks @tjmb – which version of Directus are you running? @WellingGuzman – I'm re-opening this so we can look into it a bit more.

**Comment by tjmb** [comment]
You're welcome, @benhaynes! I just downloaded Directus, so I'm using the latest version.

**Comment by WellingGuzman** [comment]
@benhaynes the issue was resolved on [development branch](https://github.com/RNGR/Directus/commit/1e6aedb1b8128f33592b87dbc18b315b94060d8a#diff-9143a416f24c99fce44d3e74c77e0fc2) also [this](https://github.com/RNGR/Directus/commit/a212135f24abf83cf81fd6d3027b001fb50ab98d#diff-71f95b96820998b70c32a7dfa64be1f5), and it hasn't been merged yet. also we need to merge development with master to fix this and other issues. 

I almost certainly sure that @tjmb is using the master branch.

Right now what you can do it's switch to development branch to fix this or wait for us to merge the development branch to master.

**Comment by tjmb** [comment]
Correct, I'm using the master branch. I'll switch to development and see if that helps.

Thanks!

**Comment by WellingGuzman** [comment]
@tjmb great, hope it helps. Let us know.
Otherwise We'd be merging the development branch with master branch soon.

**Comment by benhaynes** [comment]
OK, that's what I figured – @WellingGuzman we can do a merge whenever you feel it's appropriate (good, stable point).
