### ISSUE TITLE
Upload media, missing "temp" folder

### ISSUE THREAD

**Issue by yeahlo** [RNGR/Directus#741]
You need to create it manually before upload works.

**Comment by benhaynes** [comment]
Thoughts on this @WellingGuzman ?

**Comment by WellingGuzman** [comment]
Sorry for the late reply @yeahlo 
There's a lot of thing going on in why it's missing, one of then it's that we are offering a build (branch) which give the Directus ready to use with the directory created. we get to the conclusion we need to provide the directory anyway, because on installation it's configuring as the default `media` directory.

So as right now, the media directory is included and you don't need to create it manually.

Thanks!
