### ISSUE TITLE
Directus hanging on install - no error given.

### ISSUE THREAD

**Issue by PavlusTravel** [RNGR/Directus#754]
Going through initial setup.  It's hanging on checking mod_rewrite (no error, just halts) - you can see the screenshot below:

![directus_issue](https://cloud.githubusercontent.com/assets/5760074/7189636/74946a5c-e43d-11e4-845d-697d97d7f45c.PNG)

**Comment by WellingGuzman** [comment]
Hello @PavlusTravel,

Can you provide more info, your server setup, the rest of the pre-installation check, which branch are you trying to install? is it mod_write enabled?

What exactly happens? after you click install, it just send you back to the same page?

Thanks for letting us know.

**Comment by PavlusTravel** [comment]
I'm trying with Directus6, version 0.0.1 - You can find my server info here: http://directus.pavlus.com/my_info.php - mod_rewrite is enabled by default and triggered via .htaccess

And the screenshot above is exactly what happens when trying to install.  It stops right there.  The page stops loading, so the rest of it is blank after the mod_rewrite Enabled.  Server error log also does not show anything.

**Comment by WellingGuzman** [comment]
@PavlusTravel Yeah, I see your problem we are using apache functions, and you (server) are using Fast/CGI instead. so there's not apache functions or mod_rewrite enabled on your server.

We are working on this issue, but as right now, we need Apache and mod_rewrite enabled, that's why the page stops there, because it throws and error regarding an apache functions that does not exists, but the errors are hidden.

Thanks for letting us know that, We will work on this one.

**Comment by PavlusTravel** [comment]
Thanks for the response - I loved it on my test box, hopefully I can get it up on the dev server.  Thanks again!

**Comment by WellingGuzman** [comment]
This was resolved by #758 soon on master branch.
