### ISSUE TITLE
Deleting temp files

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#808]
Not sure if this is a global issue, but on one of my instances of Directus it seems that all the upload temp files are piling up (never being deleted) which fills all the disk space pretty quickly. Could we ensure that all temp files are being deleted?

**Comment by WellingGuzman** [comment]
I submitted an PR #812, but this solve half of the problem. we need to find a work around when the file is not saved, so my idea is to not create a temp file, as far as I know this is only being create to show a preview, we can implement `FileReader` (This won't work on older browser) or we can also return the data of the thumbnail image, don't know how great/bad this idea could be, regarding of more data to be returned. I'd give both a try and see what the best choice.

**Comment by benhaynes** [comment]
@WellingGuzman – I agree. I'd say let's abandon any old browser restrictions. If we don't need to save the temp file for any reason then let's not save it! Does that mean that we would get rid of that folder too? Is there any reason we would want/need to keep that directory?

**Comment by WellingGuzman** [comment]
@benhaynes the only reason the `temp` directory exists there is just to upload the file there in order to create a url to point to the file and show the preview on the `file ui`, so after this is done, the image should be be deleted.

I see the advantage of removing the step of uploading the file just to display a preview, we can save the process of uploading a file just to display a preview leading us to a dangling file.
But the disadvantage is that when there's not support for `FileReader` there would be no file preview (but that's ok, that probably what they get for having a old browser hehe), but for real. I think would be a good fallback to show the file name instead of the preview and would be ok, just like any other type of file.

any thoughts?

**Comment by benhaynes** [comment]
Based on this (http://caniuse.com/#feat=filereader) I would say that we should be fine to use the FileReader method. At this point it would be good to clean/refine the framework as much as possible... keep it quick and simple. So let's plan on deleting the temp folder and implementing the FileReader for preview (and Title if not supported).

Thanks!

**Comment by benhaynes** [comment]
@WellingGuzman I know we didn't remove the temp directory, but we did resolve this issue of temp files not deleting. I'll close this until we figure out how we want to handle the temp directory.
