### ISSUE TITLE
Files page assets don't seem to order properly

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#857]
I have uploaded many files and it seems as though the most recent one is never first. For example, I just uploaded a picture of the black and white cat and it shows up second... and says that it was uploaded "in six minutes" (the future). Do we have problems with the timestamp?

![screen shot 2015-07-14 at 12 11 35 pm](https://cloud.githubusercontent.com/assets/522079/8678397/54c362d4-2a22-11e5-8dc3-7c212e8a29c7.png)

**Comment by WellingGuzman** [comment]
@benhaynes I'd take a look, probably I messed up the timestamp on the new uploader. let's see.

**Comment by WellingGuzman** [comment]
While I honestly don't know when this got broken:

But disabling this get fixed:

![screen shot 2015-07-18 at 9 00 03 pm](https://cloud.githubusercontent.com/assets/1531291/8764116/b479a614-2d8f-11e5-908c-2fff505de66e.png)

When this UI settings is enabled the date value are formatted to "ago" format and it hard to sort based on  uploaded date.

I wonder was this working before? or does the settings wasn't enabled before?

@benhaynes thoughts?

**Comment by benhaynes** [comment]
@WellingGuzman 

OK, that makes sense. That parameter was to show the date (on the item listing page) as contextual (_13 min ago_) instead of the timestamp (_8:44p_). So it must be ordering by that string.

It's nice on that page to see that things were uploaded "5 seconds ago"... so hopefully there's a way to show that but still order correctly. If it's too hard, we can just show the timestamp. Thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes I mean is perfectly fin showing the date as contextual, I mean we should have a way to separate the value of the input AND the representation of the value.

I believe the value of an UI is get by the method `list` because was it meant to show its value on the listview, am I right?

so, in conclusion a suggest a UI need to be capable to have a value and a representation of the value.

Example: 

Datetime UI
---
Value | Representation of the value
------------ | -------------
1437356674 | Monday, 20-Jul-15 01:44:34 UTC
1437356674 | one seconds ago

User UI
---
Value | Representation of the value
------------ | -------------
1234 | Welling Guzman
1234 | ![Welling Guzman](https://cloud.githubusercontent.com/assets/1531291/8768991/d610f63a-2e5f-11e5-88e4-ef615f73789f.jpg)

So it doesn't matter what's the text being displayed, the value still the same. so sorting it will always end up sorting the "real" values instead the representation of the value. sorting the _ids_ of User UI instead sorting the image url or the names.

Now, while writing this what if we want to sort by names, because should be more convenient, that something to think about, what if we can specify by an options if we want to sort by "native value" or the representation value?.

This is getting a little bit complex. but it would be better to separate the value from the representation of the value.

Thoughts?

**Comment by benhaynes** [comment]
@WellingGuzman Yes! This makes sense and would be an amazing thing to have. Although, would we need this too:

Value, Representation, and *Sort*

Unless you think the value is always sortable. If they are the same then what you described would be perfect.

**Comment by WellingGuzman** [comment]
@benhaynes exactly, that's what I was trying to say  `value` would not be always sortable, in some cases is better to sort a user by its name rather that its id, on the user UI for example. so having Value, Representation and Sort is the perfect combination.

**Comment by benhaynes** [comment]
@WellingGuzman Awesome, that seems like a good plan!lingGuzman

**Comment by benhaynes** [comment]
@WellingGuzman Any updates here?

**Comment by WellingGuzman** [comment]
There's a draft implementation which works, but we need to polish it a bit more, and add the sort and value implementation on some UI, as well as implementing the image **list** on User UI.

So I'd keep updating this. regarding this issue it should be fixed by now.

**Comment by WellingGuzman** [comment]
I'd call the rest part of another issue. The file are getting sorted correctly.
I'll close this.
