### ISSUE TITLE
Directus User Images

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#859]
Hey @WellingGuzman – could you explain the "Avatar is File" column?

The way this should work is: if the user has a file uploaded then it uses that... otherwise it defaults to the Gravatar image. We should remove/hide the "Avatar is File" column unless you think it needs to be there.

![screen shot 2015-07-14 at 4 53 47 pm](https://cloud.githubusercontent.com/assets/522079/8684890/f59442f2-2a48-11e5-9178-f0243debf596.png)

**Comment by benhaynes** [comment]
Maybe this is ordered by ID and it's getting confused when it hits another digit?

999 vs 10000

I checked my preferences and they are correct, but images are all over the place in the listing view.

**Comment by WellingGuzman** [comment]
@benhaynes was the previous comment related to this issue or the issue with files being sorted all wrong?

Anyway, you are right, I'm removing that fields, so if a image is uploaded/set it automatically replace the gravatar.

I thought it would be nice to have an option where you can choose to pick the image or not, but it was kind of dumb, if someone upload the image as a avatar it is because want it as a avatar.

So it's cool to remove it.

**Comment by WellingGuzman** [comment]
Option removed!
