### ISSUE TITLE
Included "media" folder conflicts

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#863]
@WellingGuzman – Now that we have a media folder directly in the repo (and not in the gitignore) will we always have git conflicts when pulling new versions to remote servers if they already have assets in them? How can we avoid this?

**Comment by WellingGuzman** [comment]
@benhaynes we are not going to have any issue here, as now, because the media directory is empty. 

As you can see the dev server it's pulling from this branches, and it never get file conflicts.

But now, a important question here is, @benhaynes did you have an issue with git conflicts pulling new versions to remote servers?

**Comment by benhaynes** [comment]
@WellingGuzman – OK, good. I can't remember if I had an issue pulling to a remote server... since this was a month ago. But I will reopen this ticket if I notice that happening. Thanks!
