### ISSUE TITLE
Directus versioning

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#864]
@WellingGuzman Is there a way we can automatically have the version number increase with the changes we're making? I'd like this to be more regimented on the master branch now that we're getting things wrapped up. Currently I just go by the commit hash, but it'd be good to be more formal about our version numbers. Thoughts?

**Comment by WellingGuzman** [comment]
@benhaynes I was thinking about if I had not been aware of some automatically versioning, but as far as I know this need to be done manually.

Let's say, now after we wrap everything up and merge with master, on master with manually bump the version number, from 6.0.2 to 6.1.0 and tagged as a released version, we hash that version number as we get the commit hash, but is not automatically.

If we are talking about cache buster we are using from the git commit hash, we can also use the modification time from each file and each file has a different hash.

We can discuss more ideas here, like on each commit, we can automatically bump a number into a file and get the hash from there instead of the commit.

But I'd vote for using manually change our version into production (master), while we work on cache buster for the assets JS and CSS, and we work on modification time with this?

Are you thinking on anything more beside assets for the version number?

**Comment by benhaynes** [comment]
@WellingGuzman This sounds good. I wasn't sure if there was a more automated process out there... but I like this.

So let's get everything on dev nice and stable and then we can merge into master, increment the subversion, and tag a release version. Perfect!

When do you think we'll be good for another master merge? Is our DB migration up-to-date?

**Comment by WellingGuzman** [comment]
@benhaynes I think we should wait until #921, #893 and #881 are done, and after I clean up the DB Migrations so it's less files, because there's files creating tables that later we delete, at the same migration, what do you think?

after this is done, I'd work primarily  on #805 and any related to files. so we can be done with it.

Thoughts? Let's chat.

**Comment by benhaynes** [comment]
@WellingGuzman I like it... that sounds good to me!
