### ISSUE TITLE
Error trying to adjust permissions

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#868]
(Development branch) I am using the default SQL schema from the /api/schema.sql file – and I get this error when trying to adjust my permissions. Also, new tables I create in the database (directly) are not showing up under permissions.

![screen shot 2015-07-16 at 7 33 03 pm](https://cloud.githubusercontent.com/assets/522079/8737580/9424c154-2bf1-11e5-9ae5-3e8c5543de31.png)

Restricted Access
You don't have permission to access this table. Please send this to IT:
{ "message":"[Group #1 User #2] The table `directus_privileges` is missing the `user_create_column` within `directus_tables` (BigEdit Permission Forbidden)" }

**Comment by WellingGuzman** [comment]
I found the problem here, in `schema.sql` I used what we agreed to have everything default to 1, which means on update/edit, the group do not have `bigedit` permission, so it try to look up for a the user column to check if this entry belongs to the user performing the update, so it fails, and wont work.

The solutions is to set the the group to big permission. (not altering the default value being 1)

**Comment by benhaynes** [comment]
@WellingGuzman  Thanks! I had actually updated the SQL file but forgot to push it up. I will merge it in now since it has the `status_id` defaulting to NULL (which it should) and adds in comments for the table.

**Comment by WellingGuzman** [comment]
@benhaynes great, if this still happen let's reopen it.
