### ISSUE TITLE
Does it make sense to have "active" on directus_files?

### ISSUE THREAD

**Issue by benhaynes** [RNGR/Directus#883]
There is no way to make files inactive, or to delete them (as of now) through directus. When we do add the ability to delete files, would it delete the actual file or just the DB record? Maybe this should be a media setting?

![screen shot 2015-07-19 at 10 38 12 pm](https://cloud.githubusercontent.com/assets/522079/8769251/fcb3d80a-2e66-11e5-8bb4-36baf8ae5800.png)

**Comment by WellingGuzman** [comment]
@benhaynes yes, if we add the ability to delete a file, it would delete the DB record, not the actual file, because there's not way to delete a file either (as of now).

I also think having active would treat deleting file as deleting records, if there's a active, we inactive the record otherwise would delete the file and the record.

Now, what kind of scenario we want to inactive a file?

**Comment by benhaynes** [comment]
@WellingGuzman OK, I agree. I can't think of a scenario where we'd want an inactive file... but maybe it's best to soft-delete files and leave the asset on the server. That way an admin could always retrieve the record/file?

**Comment by WellingGuzman** [comment]
@benhaynes seems fair, that's the only thing I can think of now.

do we agreed on implementing soft-delete just changing the status of the db record?

**Comment by benhaynes** [comment]
Yes, I think that's best for now.

**Comment by benhaynes** [comment]
Hey @WellingGuzman how are we currently handling file deletion? If we're soft-deleting it then this ticket can be closed. My only question is, does it make sense to leave the file in the main media directory or should we move it to an inactive directory? My concern is if you upload a file with the same name it will cause an issue even though the first is "deleted".

**Comment by WellingGuzman** [comment]
@benhaynes right now we are soft-deleting files

Note: (this is how it should work, but now there's a bug in it, couldn't make it work as it suppose to)

if you upload a file with the same name it would append a number after it. `file.jpg` is uploaded and save (using file name instead of ids or hash), then you soft-delete it or not, but  if you try to uplaod a `file.jpg` again it would (or  it should) created a new file file `file-2.jpg`.

**Comment by benhaynes** [comment]
OK, then I'll close this issue since #1004 and #1003 are now open.
